apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: pj-nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pj-nodeapp
  template:
    metadata:
      labels:
        app: pj-nodeapp 
    spec:
      containers:
      - name: pj-nodeapp
        image: pichkul/pj-nodeapp:latest
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: pj-nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
